version: '3.8'

services:

  loginui:
    build:
      context: .
      dockerfile: OneID.LoginUI/Dockerfile
    container_name: oneid_loginui
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AzureAd__ClientId=SEU_CLIENT_ID
      - AzureAd__TenantId=SEU_TENANT_ID
      - AzureAd__Instance=https://login.microsoftonline.com/
      - AzureAd__CallbackPath=/signin-oidc
      - AzureAd__Domain=oneidsecure.onmicrosoft.com
    expose:
      - "80" # Só expõe pra dentro da rede Docker
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - loginui
    restart: unless-stopped
